from __future__ import annotations

from datetime import date
from decimal import Decimal
from typing import Any, Protocol, runtime_checkable
from uuid import UUID

from cogtainer.db.models import (
    Alert,
    Budget,
    BudgetPeriod,
    Conversation,
    ConversationStatus,
    Cron,
    Event,
    Memory,
    MemoryVersion,
    Program,
    Resource,
    ResourceUsage,
    Run,
    RunStatus,
    Task,
    TaskStatus,
    ThrottleResult,
    Tool,
    Trace,
    Trigger,
)


@runtime_checkable
class RepositoryProtocol(Protocol):
    # ── Raw query ────────────────────────────────────────────

    def query(self, sql: str, params: dict[str, Any] | None = None) -> list[dict]: ...
    def query_one(self, sql: str, params: dict[str, Any] | None = None) -> dict | None: ...
    def execute(self, sql: str, params: dict[str, Any] | None = None) -> int: ...

    # ── Programs ─────────────────────────────────────────────

    def upsert_program(self, program: Program) -> UUID: ...
    def get_program(self, name: str) -> Program | None: ...
    def list_programs(self) -> list[Program]: ...
    def delete_program(self, name: str) -> bool: ...

    # ── Tasks ────────────────────────────────────────────────

    def create_task(self, task: Task) -> UUID: ...
    def get_task(self, task_id: UUID) -> Task | None: ...
    def get_task_by_name(self, name: str) -> Task | None: ...
    def update_task_status(self, task_id: UUID, status: TaskStatus) -> bool: ...
    def update_task(self, task: Task) -> bool: ...
    def delete_task(self, task_id: UUID) -> bool: ...
    def list_tasks(self, *, status: TaskStatus | None = None, limit: int = 50) -> list[Task]: ...
    def upsert_task(self, task: Task, *, update_priority: bool = False) -> UUID: ...

    # ── Triggers ─────────────────────────────────────────────

    def insert_trigger(self, trigger: Trigger) -> UUID: ...
    def get_trigger(self, trigger_id: UUID) -> Trigger | None: ...
    def list_triggers(self, *, enabled_only: bool = True, program_name: str | None = None) -> list[Trigger]: ...
    def delete_trigger(self, trigger_id: UUID) -> bool: ...
    def update_trigger_enabled(self, trigger_id: UUID, enabled: bool) -> bool: ...
    def throttle_check(self, trigger_id: UUID, max_events: int, window_seconds: int) -> ThrottleResult: ...

    # ── Cron ─────────────────────────────────────────────────

    def insert_cron(self, cron: Cron) -> UUID: ...
    def upsert_cron(self, cron: Cron) -> UUID: ...
    def list_cron(self, *, enabled_only: bool = False) -> list[Cron]: ...
    def delete_cron(self, cron_id: UUID) -> bool: ...
    def update_cron_enabled(self, cron_id: UUID, enabled: bool) -> bool: ...

    # ── Events ───────────────────────────────────────────────

    def append_event(self, event: Event, *, status: str = "sent") -> int: ...
    def get_events(self, *, event_type: str | None = None, limit: int = 100) -> list[Event]: ...
    def get_event_tree(self, event_id: int) -> list[Event]: ...
    def get_event_root(self, event_id: int) -> list[Event]: ...
    def get_proposed_events(self, *, limit: int = 50) -> list[Event]: ...
    def mark_event_sent(self, event_id: int) -> bool: ...

    # ── Runs ─────────────────────────────────────────────────

    def insert_run(self, run: Run) -> UUID: ...
    def update_run(self, run: Run) -> bool: ...
    def query_runs(
        self,
        *,
        program_name: str | None = None,
        conversation_id: UUID | None = None,
        task_id: UUID | None = None,
        status: RunStatus | None = None,
        limit: int = 50,
    ) -> list[Run]: ...

    # ── Conversations ────────────────────────────────────────

    def upsert_conversation(self, conv: Conversation) -> UUID: ...
    def get_conversation_by_context(self, context_key: str) -> Conversation | None: ...
    def list_conversations(
        self,
        *,
        status: ConversationStatus | None = None,
        limit: int = 100,
    ) -> list[Conversation]: ...
    def close_conversation(self, conversation_id: UUID) -> bool: ...

    # ── Alerts ───────────────────────────────────────────────

    def create_alert(self, alert: Alert) -> UUID: ...
    def get_unresolved_alerts(self) -> list[Alert]: ...
    def resolve_alert(self, alert_id: UUID) -> bool: ...
    def resolve_all_alerts(self) -> int: ...
    def get_resolved_alerts(self, limit: int = 25) -> list[Alert]: ...
    def delete_alert(self, alert_id: UUID) -> bool: ...

    # ── Traces ───────────────────────────────────────────────

    def insert_trace(self, trace: Trace) -> UUID: ...
    def get_traces(self, run_id: UUID) -> list[Trace]: ...

    # ── Resources ────────────────────────────────────────────

    def upsert_resource(self, resource: Resource) -> str: ...
    def get_resource(self, name: str) -> Resource | None: ...
    def list_resources(self) -> list[Resource]: ...
    def delete_resource(self, name: str) -> bool: ...
    def get_pool_usage(self, resource_name: str) -> int: ...
    def get_consumable_usage(self, resource_name: str) -> float: ...
    def insert_resource_usage(self, usage: ResourceUsage) -> int: ...

    # ── Budget ───────────────────────────────────────────────

    def get_or_create_budget(
        self,
        period: BudgetPeriod,
        period_start: date,
        *,
        token_limit: int = 0,
        cost_limit_usd: Decimal = Decimal("0"),
    ) -> Budget: ...
    def record_spend(
        self,
        period: BudgetPeriod,
        period_start: date,
        *,
        tokens: int = 0,
        cost_usd: Decimal = Decimal("0"),
    ) -> Budget: ...
    def check_budget(self, period: BudgetPeriod, period_start: date) -> Budget | None: ...

    # ── Tools ────────────────────────────────────────────────

    def upsert_tool(self, tool: Tool) -> UUID: ...
    def get_tool(self, name: str) -> Tool | None: ...
    def get_tools(self, names: list[str]) -> list[Tool]: ...
    def list_tools(self, *, prefix: str | None = None, enabled_only: bool = True) -> list[Tool]: ...
    def delete_tool(self, name: str) -> bool: ...
    def update_tool_enabled(self, name: str, enabled: bool) -> bool: ...

    # ── Memory (versioned) ──────────────────────────────────

    def insert_memory(self, mem: Memory) -> UUID: ...
    def get_memory_by_name(self, name: str) -> Memory | None: ...
    def get_memory_by_id(self, memory_id: UUID) -> Memory | None: ...
    def insert_memory_version(self, mv: MemoryVersion) -> None: ...
    def get_memory_version(self, memory_id: UUID, version: int) -> MemoryVersion | None: ...
    def get_max_version(self, memory_id: UUID) -> int: ...
    def list_memory_versions(self, memory_id: UUID) -> list[MemoryVersion]: ...
    def update_active_version(self, memory_id: UUID, version: int) -> None: ...
    def update_version_read_only(self, memory_id: UUID, version: int, read_only: bool) -> None: ...
    def update_memory_includes(self, memory_id: UUID, includes: list[str]) -> None: ...
    def update_memory_name(self, memory_id: UUID, new_name: str) -> None: ...
    def delete_memory(self, memory_id: UUID) -> None: ...
    def delete_memory_version(self, memory_id: UUID, version: int) -> None: ...
    def list_memories(
        self,
        *,
        prefix: str | None = None,
        source: str | None = None,
        limit: int = 200,
    ) -> list[Memory]: ...
    def resolve_memory_keys(self, keys: list[str]) -> list[Memory]: ...
